# Uygulama ad? (opsiyonel)
spring.application.name=restaurant-management

# =====================================================
# PostgreSQL ba?lant? bilgileri (Docker için önemli!)
# 'localhost' yerine 'db' yaz?yoruz çünkü Docker'da
# servis ismi DNS görevi görüyor.
# =====================================================
spring.datasource.url=jdbc:postgresql://db:5432/restoran_db
spring.datasource.username=postgres
spring.datasource.password=123456

# =====================================================
# Hibernate ayarlar?
# 'update' -> tablo yoksa olu?turur, varsa dokunmaz
# =====================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
